import { createHash } from 'node:crypto';
import type { FastifyInstance } from 'fastify';

// No trackers or third-party assets; credentials stay in the URL fragment until cleared.
const script = `const language=(navigator.language||'en').slice(0,2);const t=({tr:['Şifre sıfırlama','E-posta','Yeni şifre (en az 6 karakter)','Gönder','Hesap varsa bağlantı e-postaya gönderildi.','Şifre güncellendi. Giriş yapabilirsiniz.','İşlem tamamlanamadı. Yeni bağlantı isteyin.'],de:['Passwort zurücksetzen','E-Mail','Neues Passwort (mindestens 6 Zeichen)','Senden','Falls das Konto existiert, wurde ein Link gesendet.','Passwort geändert. Sie können sich anmelden.','Vorgang fehlgeschlagen. Bitte einen neuen Link anfordern.']}[language]||['Password reset','Email','New password (at least 6 characters)','Submit','If the account exists, a link has been sent.','Password changed. You can sign in.','Unable to complete. Please request a new link.']);document.documentElement.lang=['tr','de'].includes(language)?language:'en';document.title=t[0];document.querySelector('h1').textContent=t[0];const token=new URLSearchParams(location.hash.slice(1)).get('token');history.replaceState(null,'',location.pathname);const input=document.querySelector('input');input.type=token?'password':'email';input.name=token?'password':'email';input.autocomplete=token?'new-password':'email';if(token)input.minLength=6;document.querySelector('label').textContent=t[token?2:1];document.querySelector('button').textContent=t[3];document.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('button');button.disabled=true;try{const response=await fetch(location.pathname+(token?'/confirm':'/request'),{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify(token?{token,password:input.value}:{email:input.value})});if(!response.ok)throw new Error('request_failed');document.querySelector('[role=status]').textContent=t[token?5:4];input.value='';if(token)document.querySelector('form').hidden=true;}catch{document.querySelector('[role=status]').textContent=t[6];}finally{button.disabled=false;}});`;
const scriptHash=createHash('sha256').update(script).digest('base64');
export function registerPasswordResetPage(app: FastifyInstance) {
  app.get('/auth/password-reset',async (_req,reply)=>reply
    .header('Cache-Control','no-store')
    .header('Referrer-Policy','no-referrer')
    .header('X-Robots-Tag','noindex, nofollow')
    .header('Content-Security-Policy',`default-src 'none'; script-src 'sha256-${scriptHash}'; style-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`)
    .type('text/html; charset=utf-8').send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Password reset</title><style>body{font:18px system-ui;margin:3rem auto;padding:1rem;max-width:32rem;color:#182b38}label,input,button{display:block;margin:1rem 0}input,button{font:inherit;padding:.7rem;box-sizing:border-box;width:100%}button{cursor:pointer}h1{font-size:1.8rem}</style></head><body><main><h1>Password reset</h1><form><label for="reset-input">Email</label><input id="reset-input" type="email" required maxlength="254"><button>Submit</button></form><p role="status" aria-live="polite"></p><noscript>JavaScript is required / JavaScript gereklidir / JavaScript erforderlich.</noscript></main><script>${script}</script></body></html>`));
}
